server:
  port: 8081

spring:
  application:
    name: player_two

game:
  other-player:
    play-url: http://localhost:8080/api/v1/game/play
    start-url: http://localhost:8080/api/v1/game/start-game
  random-number:
    min: 10
    max: 1000
